---
- hosts: all
  become: yes
  vars:
     DEB_URL: https://dl.grafana.com/oss/master/grafana_7.3.0~575113c1pre_amd64.deb
  tasks:

    - name: update
      apt: update_cache=yes   
     
    - name: Installing Grafana
      apt:
        deb: "{{ DEB_URL }}"

    - name: Starting Grafana service.
      service: name=grafana-server state=started
